# Generated by cpp11: do not edit by hand

ods_get_sheet_names <- function(file, include_external_data) {
  .Call(`_readODScpp_ods_get_sheet_names`, file, include_external_data)
}

read_ods_ <- function(file, start_row, stop_row, start_col, stop_col, sheet) {
  .Call(`_readODScpp_read_ods_`, file, start_row, stop_row, start_col, stop_col, sheet)
}
