# Generated by cpp11: do not edit by hand

ods_get_sheet_names <- function(file, include_external_data) {
  .Call(`_readODScpp_ods_get_sheet_names`, file, include_external_data)
}

get_cell_range <- function(file, sheet) {
  .Call(`_readODScpp_get_cell_range`, file, sheet)
}
